version: "3"
services:
  poster_server:
    container_name: poster_server
    restart: always
    build: ./server/
    ports:
      - "4000:4000"
    volumes:
      - ./server:/usr/src/app
    links:
      - poster_db

  poster_db:
    container_name: poster_db
    image: mongo
    ports:
      - "27018:27017"
    command: --quiet
    logging:
      driver: "none"

  poster_client:
    container_name: poster_client
    restart: always
    build: ./client/
    ports:
      - "4001:4001"
    volumes:
      - ./client:/usr/src/app
