version: "3"
services:
  poster_server:
    container_name: poster_server
    restart: always
    build: ./server/
    ports:
      - "4000:4000"
    volumes:
      - ./server:/usr/src/app
    entrypoint: ./wait-for-it.sh poster_db:27017 -- npm run dev:watch #wait for the db image to be ready
    environment: 
         NODE_ENV: development

  poster_db:
    container_name: poster_db
    image: mongo
    ports:
      - "27018:27017" # "host:container"
    command: --quiet
    logging:
      driver: "none"

  poster_client:
    container_name: poster_client
    restart: always
    build: ./client/
    ports:
      - "4001:4001"
    volumes:
      - ./client:/usr/src/app
